[package]
edition = "2021"
name    = "voyager-transaction-module-aptos"
version = "0.1.0"

[dependencies]
aptos-crypto      = { workspace = true }
aptos-rest-client = { workspace = true }
aptos-types       = { workspace = true }
move-core-types   = { workspace = true }

bcs                = "0.1.6"
bip32              = { workspace = true }
chain-utils        = { workspace = true }
enumorph           = { workspace = true }
frunk              = { workspace = true }
futures            = { workspace = true }
jsonrpsee          = { version = "0.24.1", features = ["macros", "server", "tracing"] }
macros             = { workspace = true }
move-bindgen       = { workspace = true }
queue-msg          = { workspace = true }
serde              = { workspace = true, features = ["derive"] }
serde-utils        = { workspace = true }
serde_json         = { workspace = true }
sha3               = { workspace = true }
thiserror          = { workspace = true }
tokio              = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
unionlabs          = { workspace = true }
voyager-message    = { workspace = true }
