[package]
authors = []
name    = "ibc-api"
version = "1.0.0"

[addresses]
ibc_api = "_"

[dev-addresses]
ibc_api = "0x9991"

[dependencies.AptosFramework]
git    = "https://github.com/aeryz/aptos-core.git"
rev    = "c608cfceddab39d5b626ccd332409efb6ae78c08"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
