base = "result"
exclude = [
  '^tcp://',
  '.woff2$',
  '^https://grpc',
  '^udhc.finance',
  '^https://x.com',
  '^https://discord.',
  '^https://twitter.com',
  '^http://myserver.com',
  '^https://nodeist.net/union',
  '^https://services.staketab.org',
  '^https://statesync.testnet.bonlulu.uno',
  '^https://union-testnet-grpc.polkachu.com',
]

exclude_all_private = true
exclude_link_local  = true
