[package]
description = """
Utility library for launching NEAR sandbox environments.
"""
edition = "2018"
license = "MIT OR Apache-2.0"
name = "near-sandbox-utils"
repository = "https://github.com/near/sandbox"
version = "0.7.1"

[dependencies]
anyhow         = "1"
binary-install = "0.2.0"
chrono         = "0.4"
fs2            = "0.4"
home           = "0.5.5"
tokio          = { version = "1", features = ["process"] }

[features]
global_install = []
