[package]
authors = []
name    = "move-ibc"
version = "1.0.0"

[addresses]
IBC                  = "_" # This will be storage of our IBCStore
IBCModuleAddr        = "_"

[dev-addresses]
IBC = "0x11111"
IBCModuleAddr = "0x333333333333333"

[dependencies.AptosFramework]
git    = "https://github.com/aeryz/aptos-core.git"
rev    = "c608cfceddab39d5b626ccd332409efb6ae78c08"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
