[package]
authors = []
name    = "move-ibc"
version = "1.0.0"

[addresses]
IBC                  = "0x111111111111111" # This will be storage of our IBCStore
IBCModuleAddr        = "0x333333333333333"
mock_relayer_address = "0x222222222222222"

[dev-addresses]

[dependencies.AptosFramework]
git    = "https://github.com/aptos-labs/aptos-core.git"
rev    = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
