[package]
authors = []
name    = "ibc"
version = "1.0.0"

[addresses]
IBC = "0x11111" # This will be storage of our IBCStore

[dev-addresses]
IBC = "0x11111"

[dependencies.AptosFramework]
git    = "https://github.com/aeryz/aptos-core.git"
rev    = "17c10f224fd6d76101881799de3cf49750acfe03"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]



