[build]
base    = "site/"
command = "npm_config_yes=true npx astro@latest build"
ignore  = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./site/"
publish = "dist"

[build.processing.html]
pretty_urls = true

[[redirects]]
from = "/docs"
to = "https://docs.union.build"
status = 301
