[package]
edition.workspace      = true
license-file.workspace = true
name                   = "ics08-movement"
repository.workspace   = true
version                = "0.1.0"

[dependencies]
hex = { workspace = true, features = ["alloc"] }
aptos-verifier     = { workspace = true }
bcs                = { git = "https://github.com/aptos-labs/bcs.git", rev = "d31fab9d81748e2594be5cd5cdf845786a30562d" }
cosmwasm-std       = { workspace = true, features = ["abort"] }
ethereum-verifier  = { workspace = true }
hex-literal        = { workspace = true }
ics008-wasm-client = { workspace = true }
protos             = { workspace = true }
rlp                = { workspace = true }
serde              = { workspace = true, features = ["derive"] }
serde_json         = { workspace = true }
sha2               = { workspace = true, features = ["std"] }
sha3               = { workspace = true }
thiserror          = { workspace = true }
unionlabs          = { workspace = true, features = ["cosmwasm", "stargate"] }

[dev-dependencies]
aptos-types = { git = "https://github.com/movementlabsxyz/aptos-core" }
aptos-crypto = { git = "https://github.com/movementlabsxyz/aptos-core" }

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]
