[package]
authors = ["Jacob Lindahl <jacob.lindahl@near.org>"]
edition = "2021"
name = "near-ibc"
version = "0.1.0"

[dependencies]
near-contract-standards = "4.1.1"
near-sdk = "4.1.1"
near-sdk-contract-tools = "2.1.0"
ibc-vm-rs.workspace = true
serde_json.workspace = true
serde.workspace = true
borsh = { version = "1.5.0", features = ["borsh-derive"] }
unionlabs.workspace = true
thiserror.workspace = true

[lib]
crate-type = ["cdylib"]

[lints.clippy]
pedantic = "warn"
missing-panics-doc = "allow"
module-name-repetitions = "allow"
must-use-candidate = "allow"
needless-pass-by-value = "allow"
wildcard-imports = "allow"
