[package]
authors = ["Jacob Lindahl <jacob.lindahl@near.org>"]
edition = "2021"
name    = "dummy-ibc-app"
version = "0.1.0"

[dependencies]
borsh                   = { version = "1.5.0", features = ["borsh-derive"] }
ibc-vm-rs.workspace     = true
near-contract-standards = { workspace = true }
near-sdk                = { workspace = true }
near-sdk-contract-tools = "2.1.0"
serde.workspace         = true
serde_json.workspace    = true
unionlabs.workspace     = true

[dev-dependencies]
anyhow     = "1.0"
near-units = "0.2.0"
tokio      = { version = "1.18.1", features = ["full"] }
workspaces = "0.7.0"

[lib]
crate-type = ["cdylib"]

[lints.clippy]
missing-panics-doc      = "allow"
module-name-repetitions = "allow"
must-use-candidate      = "allow"
needless-pass-by-value  = "allow"
pedantic                = "warn"
wildcard-imports        = "allow"
