[package]
edition = "2021"
name    = "voyager-chain-module-ethereum"
version = "0.1.0"

[dependencies]
beacon-api         = { workspace = true }
chain-utils        = { workspace = true }
contracts          = { workspace = true, features = ["providers"] }
enumorph.workspace = true
ethers             = { workspace = true, features = ["rustls", "ws"] }
frunk.workspace    = true
futures.workspace  = true
jsonrpsee          = { version = "0.24.1", features = ["macros", "server", "tracing"] }
macros.workspace   = true
queue-msg          = { workspace = true }
serde              = { workspace = true, features = ["derive"] }
serde-utils.workspace = true
serde_json         = { workspace = true }
thiserror          = { workspace = true }
tokio              = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
unionlabs          = { workspace = true }
voyager-message    = { workspace = true }
