[package]
name = "aptos-move-ibc"
version = "0.1.0"
edition.workspace = true
license-file.workspace = true
repository.workspace = true

[dependencies]
move-bindgen  = {workspace = true}
tracing  = {workspace = true}

[lints]
workspace = true
