[package]
edition = "2021"
name    = "voyager-chain-module-movement"
version = "0.1.0"

[dependencies]
aptos-crypto              = { workspace = true }
aptos-rest-client         = { workspace = true }
aptos-types               = { workspace = true }
bcs                       = "0.1.6"
clap                      = { workspace = true, features = ["derive"] }
enumorph.workspace        = true
frunk.workspace           = true
futures.workspace         = true
hex-literal               = "0.4.1"
hex.workspace             = true
jsonrpsee                 = { workspace = true, features = ["macros", "server", "tracing"] }
macros.workspace          = true
move-bindgen              = { workspace = true }
move-core-types.workspace = true
prost.workspace           = true
protos.workspace          = true
queue-msg                 = { workspace = true }
serde                     = { workspace = true, features = ["derive"] }
serde-utils               = { workspace = true }
serde_json                = { workspace = true }
sha3.workspace            = true
thiserror                 = { workspace = true }
tokio                     = { workspace = true }
tracing                   = { workspace = true }
tracing-subscriber        = { workspace = true }
unionlabs                 = { workspace = true }
voyager-message           = { workspace = true }
