[package]
edition = "2021"
name    = "voyager-chain-module-movement"
version = "0.1.0"

[dependencies]
aptos-rest-client  = { workspace = true }
clap               = { workspace = true, features = ["derive"] }
enumorph.workspace = true
frunk.workspace    = true
futures.workspace  = true
jsonrpsee          = { version = "0.24.1", features = ["macros", "server", "tracing"] }
macros.workspace   = true
prost.workspace    = true
protos.workspace   = true
queue-msg          = { workspace = true }
serde              = { workspace = true, features = ["derive"] }
serde-utils        = { workspace = true }
serde_json         = { workspace = true }
thiserror          = { workspace = true }
tokio              = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
unionlabs          = { workspace = true }
voyager-message    = { workspace = true }
