[package]
authors      = ["Hussein Ait Lahcen <hussein.aitlahcen@gmail.com>"]
edition      = { workspace = true }
license-file = { workspace = true }
name         = "ibc-contract"
repository   = "https://github.com/unionlabs/union"
version      = "1.0.0"

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
library = []

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { version = "2.0.0-rc.1" }
cw-storage-plus = { version = "2.0.0" }
dlmalloc        = { workspace = true, features = ["global"] }
ethabi          = { workspace = true }
serde           = { workspace = true, features = ["derive"] }
thiserror       = { workspace = true }
ibc-vm-rs       = { workspace = true }

[dev-dependencies]
hex        = { workspace = true }
serde_json = { workspace = true }
