[package]
edition = "2021"
name    = "voyager-consensus-module-movement"
version = "0.1.0"

[dependencies]
aptos-rest-client = { workspace = true }
aptos-types       = { workspace = true }
move-core-types   = { workspace = true }

bitvec.workspace   = true
chain-utils        = { workspace = true }
enumorph.workspace = true
ethers             = { workspace = true, features = ["rustls", "ws"] }
frunk.workspace    = true
futures.workspace  = true
jsonrpsee          = { version = "0.24.1", features = ["macros", "server", "tracing"] }
macros.workspace   = true
num-bigint         = "0.4.6"
prost.workspace    = true
protos.workspace   = true
queue-msg          = { workspace = true }
reqwest            = { workspace = true, features = ["json"] }
serde              = { workspace = true, features = ["derive"] }
serde_json         = { workspace = true }
thiserror          = { workspace = true }
tokio              = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
unionlabs          = { workspace = true }
voyager-message    = { workspace = true }
