[package]
edition = "2021"
name    = "voyager-consensus-module-cometbls"
version = "0.1.0"

[dependencies]
voyager-message      = { workspace = true }
cometbft-rpc       = { workspace = true }
dashmap            = { workspace = true }
enumorph.workspace = true
frunk.workspace    = true
futures.workspace  = true
jsonrpsee          = { version = "0.24.1", features = ["macros", "server", "tracing"] }
macros.workspace   = true
num-bigint         = "0.4.6"
prost.workspace    = true
protos.workspace   = true
queue-msg          = { workspace = true }
serde              = { workspace = true, features = ["derive"] }
serde_json         = { workspace = true }
thiserror          = { workspace = true }
tokio              = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
unionlabs          = { workspace = true }
