[package]
name = "cometbls-light-client"
version = "1.0.0"
authors = []

[addresses]
hello_blockchain = "_"

[dev-addresses]
hello_blockchain = "0x2"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
