[package]
authors                = ["Union Labs"]
edition.workspace      = true
license-file.workspace = true
name                   = "ics08-near"
repository.workspace   = true
version                = "0.1.0"

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bytes           = { workspace = true }
cosmwasm-std    = { workspace = true, features = ["abort", "iterator"] }
dlmalloc        = { workspace = true, features = ["global"] }
hex             = { workspace = true }
prost           = { workspace = true }
protos          = { workspace = true, features = ["proto_full", "std"] }
ripemd          = { workspace = true }
schemars        = { workspace = true }
serde           = { workspace = true, features = ["derive"] }
serde-json-wasm = { workspace = true }
serde-utils     = { workspace = true }
sha2            = { workspace = true }
sha3            = { workspace = true }
thiserror       = { workspace = true }
cw-storage-plus = { workspace = true }

ics008-wasm-client = { workspace = true }
unionlabs          = { workspace = true, features = [ "near" ] }
near-primitives-core = { version = "0.21" }
near-verifier = { workspace = true }

[dev-dependencies]
base64      = { workspace = true }
lazy_static = "1.4.0"
serde_json  = { workspace = true }
