CONFIG_NAME: minimal
PRESET_BASE: minimal

# # Genesis
# GENESIS_FORK_VERSION: 0x000000fd

# # Altair
# ALTAIR_FORK_VERSION: 0x010000fd
ALTAIR_FORK_EPOCH: 0 
# # Bellatrix
# BELLATRIX_FORK_VERSION: 0x020000fd
BELLATRIX_FORK_EPOCH: 0
# # Capella
# CAPELLA_FORK_VERSION: 0x030000fd
CAPELLA_FORK_EPOCH: 0
# # Deneb
# DENEB_FORK_VERSION: 0x040000fd
# DENEB_FORK_EPOCH: 0


# # Time parameters
# SECONDS_PER_SLOT: 12
# SLOTS_PER_EPOCH: 6

# Deposit contract
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242
