name: Check

on:
  pull_request:
    branches:
    - main

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  commit-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0
      - name: Check for LFS files
        run: ./.github/scripts/lfs.sh
      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v5
        with:
          failOnWarnings: true

  spell-fmt-check:
        uses: unionlabs/workflows/.github/workflows/build.yml@93f1339fbc51f0c2cfca29d7c365c56816f42262
        secrets:
          nixbuild_token: ${{ secrets.nixbuild_token }}
          access-tokens: github.com=${{ secrets.GITHUB_TOKEN }}
        with:
          filter_builds: |
            (
              (.top_attr == "checks") and
              (.system == "x86_64-linux") and 
              ( 
                (
                  # Do not run on both systems
                  [.attr] | inside(
                    [
                      "spellcheck",
                      "treefmt-check"
                    ]
                  )
                )
              )
            )
