name: Links Checker

on:
  workflow_dispatch:
  repository_dispatch:
  # daily check
  schedule:
    - cron: '00 18 * * *'

defaults:
  run:
    shell: bash

env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  daily-link-checker:
    name: '🔗 Check Links'
    runs-on: ['ubuntu-latest']
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: nixbuild/nix-quick-install-action@v26
        with:
          nix_on_tmpfs: false
          nix_conf: |
            experimental-features = nix-command flakes
            access-tokens = ${{ secrets.GITHUB_TOKEN }}
      - uses: nixbuild/nixbuild-action@968e447093b702c0ab3e78d53eea1c38da1b1d0a
        with:
          nixbuild_token: ${{secrets.nixbuild_token}}

      - run: mkdir dump
      - run: nix copy --to file://`pwd`/dump --from ssh-ng://eu.nixbuild.net `nix eval --raw .#packages.x86_64-linux.site` --extra-experimental-features nix-command
      - run: cat dump/nar/*.nar.xz | xz -dc | nix-store --restore result

      - name: Link Check
        id: lychee
        uses: lycheeverse/lychee-action@v1.9.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: |
            --no-progress
            'result/**/index.html'

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: |
            C-dead-link
