name: Test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    uses: unionlabs/workflows/.github/workflows/build.yml@2c94f6f3acb2d7d9222f8fa05f43eb8c3ed2e758
    secrets:
      nixbuild_token: ${{ secrets.nixbuild_token }}
      access-tokens: github.com=${{ secrets.GITHUB_TOKEN }}
    with:
      filter_builds: |
        (
          (.top_attr == "checks") and
          (.system == "x86_64-linux") and 
          ( 
            (
              # Do not run
              [.attr] | inside(
                [
                  "ensure-blocks",
                  "epoch-completes",
                  "forced-set-rotation",
                  "pre-commit",
                  "pre-commit-check",
                  "sepolia-runs",
                  "spellcheck",
                  "treefmt-check",
                  "union-runs",
                  "virtualisation-works"
                ]
              )
            ) | not
          )
        )
